FROM node:23-alpine3.20 as builder

WORKDIR /app

COPY package*.json ./

Run yarn install 


FROM node:23-alpine3.20 as developer

COPY  --from=builder /app/node_modules /app/node_modules

COPY  . . 

RUN npm run build

FROM node:23-alpine3.20 as runer



CMD [ "executable" ]


