import StoreProvider from '@/lib/redux/store-provider';
import ConfigReactQuery from '@/lib/react-query/config-react-query';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { ProviderContext } from '@/hook/useContext';
import 'react-quill/dist/quill.snow.css';
const roboto = Roboto({
	weight: '400',
	subsets: ['latin'],
});
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="vi">
			<body
				className={roboto.className}
				style={{
					padding: '0',
					margin: '0',
				}}
			>
				<AntdRegistry>
					<StoreProvider>
						<ProviderContext>
							<ConfigReactQuery>{children}</ConfigReactQuery>
						</ProviderContext>
					</StoreProvider>
				</AntdRegistry>
			</body>
		</html>
	);
}
